# Site settings
title: LinkedPipes Visualization
email: klimek@opendata.cz
author: 
    name: "Jakub Klímek"
    twitter: jakub_klimek

description: > # this means to ignore newlines until "baseurl:"
  LinkedPipes Visualization - Vocabulary based visualization tool for Linked Data
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://visualization.linkedpipes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

sass:
    sass_dir: _sass
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
